### ISSUE TITLE
Allow starting the service without a notificaion

### ISSUE THREAD

**Issue by hsjoberg** [05nelsonm/TorOnionProxyLibrary-Android#33]
# Description
Right now, even if you do not specify a notification with `TorServiceController.Builder`, when calling `TorServiceController.startTor()` a default one wlll be shown. I would like the ability to not show one at all.

AFAICT this should be fine as long as there is a visible activity or another foreground service exists. https://developer.android.com/about/versions/oreo/background#services

## Context

This is important for me because I want my app to be integrated with Tor without explicitly telling the user via a notification (this is known and consented by the user inside the app). Tor is just one feature for me.

## Possible Implementation

I haven't looked at the code, but presumably it should be possible to just not create the notification if a flag is set.

**Comment by 05nelsonm** [comment]
Hmm. Right now the service is being started by calling `startForegroundService` for API 26+, or `startService` for APIs 16-25. Utilization of `startForegroundService` requires a foreground notification to be present, otherwise it'll crash.

Also, every action called from the `TorServiceController.Companion` (start/stop/restart/newId) makes that `startForegroundService`/`startService` call, as it's cheaper and more secure than running a `BroadcastManager` to pass the Intents (Because you cannot use a LocalBroadcastManager and pending intents for notification actions).

What if an option existed during initialization to set the notification's importance level such that it will be in the user's notification tray, but will not be visible unless the tray is pulled down and then expanded?

**Comment by 05nelsonm** [comment]
Actually, I'm re-thinking this whole process now to use Kotlin Flow. Will play with it this week to see what I can do ;-D.
